Add thriftserver SPARK_MODE support
bitnami/bitnami-docker-spark pull request #42
Opened 2021-08-11 08:55 UTC by tfoldi

**Description of the change**

In our environments, we tend to deploy Spark Thriftserver for SQL access. To this, I added `SPARK_MODE=thriftserver` that executes `start-thriftserver.sh` from `run.sh`.  In `thriftserver` mode during the startup the container initializes an empty hive metastore. 

As Thriftserver runs only in clean deployment mode, I added a new environment variable `SPARK_DRIVER_HOST` to make it possible to run inside Kubernetes. With this environment variable, Kubernetes deployments can pass the podIp to use that for internal communication between the driver and workers. 

**Benefits**

From now you can easily create a Spark SQL environment with internal or external metastore, accessible from JDBC/ODBC tools such as beeline, Tableau, or others. 

**Possible drawbacks**

Not 
**Applicable issues**

No issue was raised.

2021-08-12 11:38 UTC, alemorcuq requested changes
Thanks for the PR, @tfoldi. Please, check my comments.

2021-08-12 11:38 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    if [[ "$SPARK_MODE" != "master" ]]; then
If `SPARK_MASTER_URL` is required for thriftserver as well we should update the error message two lines below this one.

2021-08-12 11:38 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +        fi
This is only executed if `SPARK_DRIVER_HOST` is not defined. Am I missing something?

2021-08-12 11:38 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set "spark.sql.warehouse.dir" "/tmp"
Does it make sense to use a directory under `/opt/bitnami/spark`?

2021-08-12 11:38 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +        if [ "$SPARK_MODE" == "thriftserver" ]; then
Please, use double `[[ ]]`

2021-08-12 11:38 UTC, alemorcuq commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +
Remove this extra line.

2021-08-12 11:38 UTC, alemorcuq commented on README.md
> +* SPARK_DRIVER_HOST: Internal IPv4 address of the container. No defaults.
Can you add this variable to the `libspark.sh` as well.

2021-08-12 17:41 UTC, tfoldi commented
huh, based on the code review this was the most terrible PR for this repo. I'll fix things (and test it more carefully) and update the PR in a day or so

2021-08-13 05:35 UTC, tfoldi commented
One question, shall I add a container thriftserver to the docker-compose?

2021-08-18 07:44 UTC, pablogalegoc commented
@tfoldi would you say that setting up a thriftserver is a common use case? If that's the case we can add it, if not we can always add a quick reference for a `docker run ...` in https://github.com/bitnami/bitnami-docker-spark#setting-up-a-spark-cluster
BTW thanks for your work!

2021-08-18 11:10 UTC, tfoldi commented
I might be biased but most of my enterprise customers want to access their Spark tables thru ODBC/JDBC tools like Tableau, Looker, DBeaver/DataGrip or from their web apps with `hive2` connector. I think it is a pretty legit and common use case, and without extensive customizations we cannot cleanly add thrift server management to bitnami containers.

As our clients rely on these containers in their large-scale production Kubernetes systems adding this mode would definitely help my team.

2021-08-18 13:30 UTC, pablogalegoc commented
@tfoldi my fault, I worded badly my question, it was in regards to the _shall I add a container thriftserver to the docker-compose?_ If you think that's something useful to have "by default" for development environments or for more casual users then we can add it, otherwise a quick
```bash
$ docker run -d --name spark-thriftserver \
  -e SPARK_MODE=thriftserver \
  bitnami/spark
```
in the [setting up a spark cluster](https://github.com/bitnami/bitnami-docker-spark#setting-up-a-spark-cluster) section of the README could be enough

2021-08-20 08:01 UTC, tfoldi commented
I think adding to the README is enough, no need to add to the compose file (thrift server makes real sense when you are using it with a persistent hive metastore anyway).  thank you!

2021-08-23 09:37 UTC, pablogalegoc commented
@tfoldi I'll take charge of the review of this PR since @alemorcuq is on PTO, so I'll need some time to get the full context and run some tests, will get back to you as soon as I possible. Thanks again!

2021-08-24 09:02 UTC, rafariossaa commented
Hi,
  Just a quick question, when is called the function `spark_set_driver_host` ?

2021-08-25 05:50 UTC, tfoldi commented
Another set of code that I forgot to merge from my codebase :(

Anyway, I added to the end of the `spark_initialize` function. As we are using `ConfigMap` mounted `spark-default.conf`, the the call to `spark_set_driver_host` should be outside of the `if [[ ! -f "$SPARK_CONF_FILE" ]]` check. 

Does this look okay on your side too? I tested it with and without the `SPARK_DRIVER_HOST` env and works fine for me.

2021-08-25 05:52 UTC, tfoldi commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set spark.driver.host "${SPARK_DRIVER_HOST}"
I decided to make it possible to use hostnames as well, not just IP address (we always used IPs)

2021-08-25 05:52 UTC, tfoldi commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +        spark_set_driver_host
Added the missing spark_set_driver_host invocation

2021-08-25 16:43 UTC, pablogalegoc reviewed
@tfoldi first of all, thank you very much for your work, I've read documentation and talked to teammates and some questions came up. I left them below

2021-08-25 16:43 UTC, pablogalegoc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    warehouse_dir="/opt/bitnami/spark/work/warehouse"
I would use add another variable (`SPARK_WAREHOUSEDIR`) below `# Spark directories` in line 26, just in case `SPARK_BASEDIR` changes in the future, and use it here

2021-08-25 16:43 UTC, pablogalegoc commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +            spark_default_hive_metastore
[Cloudera's](https://docs.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_hive_metastore_configure.html#topic_18_4_1__section_zzx_cvv_ls) and [Databricks'](https://docs.gcp.databricks.com/data/metastores/external-hive-metastore.html) docs state that the embedded Hive Metastore is not recommended for production use so enabling this behaviour by default could be problematic when adding the functionality to the Spark chart. I think we should make it configurable and use `spark_default_hive_metastore` as the last option, what do you think?

2022-07-28 14:56 UTC, carrodher commented
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single repository: `bitnami/containers`.

Please could you create this PR in the [`bitnami/containers` monorepository](https://github.com/bitnami/containers)? Thank

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

2022-07-28 14:56 UTC, closed without merging