Update docker-compose.yml
bitnami/bitnami-docker-spark pull request #54
Opened 2021-11-11 23:09 UTC by gbeaven90

In response to the ticket I opened: #53 

This has fixed my issue:

Removed repeating spark-worker-1,spark-worker-2 from the .yml file and replaced with `spark-worker` for reusability in the docker-compose command.

Also updated `spark:3` to `spark:latest` like the documentation specifies.

Now running `docker-compose up --scale spark-worker=10` creates 10 worker instances as expected:
![image](https://user-images.githubusercontent.com/22197442/141381770-2b7fe1bc-e1d8-4600-b3d4-5ca3c35b0a89.png)

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

2021-11-12 10:24 UTC, alvneiayu requested changes
hi @gbeaven90 

First of all, thanks a lot for your PR and your time.

I included some review comments. I will test the change in our pipeline, after you apply the comments suggested.

thanks a lot

Álvaro

2021-11-12 10:24 UTC, alvneiayu commented on 3/debian-10/docker-compose.yml
> -    image: docker.io/bitnami/spark:3
could you keep without change the docker.io/bitnami/spark:3, please?

2021-11-12 10:24 UTC, alvneiayu commented on 3/debian-10/docker-compose.yml
> -    image: docker.io/bitnami/spark:3
same here

2021-11-12 10:24 UTC, alvneiayu commented on 3/debian-10/docker-compose.yml
> -    image: docker.io/bitnami/spark:3
same here

2021-11-12 10:24 UTC, alvneiayu commented on docker-compose.yml
> -    image: docker.io/bitnami/spark:3
same here

2021-11-12 10:24 UTC, alvneiayu commented on docker-compose.yml
> -    image: docker.io/bitnami/spark:3
same here

2021-11-12 10:24 UTC, alvneiayu commented on docker-compose.yml
> -    image: docker.io/bitnami/spark:3
same here

2021-11-12 15:47 UTC, gbeaven90 commented on 3/debian-10/docker-compose.yml
> -    image: docker.io/bitnami/spark:3
spark-worker-2 no longer exists, it's just spark-worker now, so this one doesn't apply.

2021-11-12 15:48 UTC, gbeaven90 reviewed
Changed tag version from 'latest' back to '3' in all applicable file updates.

2021-11-12 15:48 UTC, gbeaven90 commented on docker-compose.yml
> -    image: docker.io/bitnami/spark:3
spark-worker-2 no longer exists, it's just spark-worker now, so this one doesn't apply.

2021-11-23 15:56 UTC, alvneiayu commented
hi @gbeaven90 

I didn't answer you because I am changing some test in our pipeline to land your change. I will come back as soon as possible.

Thanks a lot

Álvaro

2021-11-26 08:10 UTC, alvneiayu approved these changes
LGTM

2021-11-26 08:10 UTC, merged