Set spark.ssl.port based on SPARK_WEBUI_SSL_PORT var
bitnami/bitnami-docker-spark pull request #64
Opened 2022-01-06 13:43 UTC by brsolomon-deloitte

This changed is tied to https://github.com/bitnami/charts/pull/8447 and provides a way for upstream to set a `SPARK_WEBUI_SSL_PORT` environment variable that will in turn dictate `spark.ssl.port`.

2022-01-07 08:54 UTC, carrodher commented
Thanks for creating this issue and the associated PR. The Bitnami team will check the PR usually during a business day.

2022-01-10 08:43 UTC, migruiz4 requested changes
Hi @brsolomon-deloitte,

Thank you very much for your contribution! Please check my comment below.

In addition, it is missing one more thing. The variable `SPARK_WEBUI_SSL_PORT` needs to be defined in the bash function `spark_env` empty by default so it takes [Spark's default](https://spark.apache.org/docs/latest/security.html) when not set:
https://github.com/bitnami/bitnami-docker-spark/blob/007ff07f030d35d8f1f555b39915eaf39451495a/3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh#L24-L65

2022-01-10 08:43 UTC, migruiz4 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set spark.ssl.port "${SPARK_WEBUI_SSL_PORT}"
Could you please make it conditional whether `SPARK_WEBUI_SSL_PORT` is empty or not?

2022-01-10 14:20 UTC, brsolomon-deloitte commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set spark.ssl.port "${SPARK_WEBUI_SSL_PORT}"
Okay, I see what you mean. Change made. I see in the docs that:

> When not set, the SSL port will be derived from the non-SSL port for the same service. A value of "0" will make the service bind to an ephemeral port.

So its default is dynamic. Therefore I did not define it within `spark_env` but rather just checked if the downstream e.g. K8s has specified it explicitly.

> 21/12/17 16:00:41 INFO Utils: Successfully started service 'MasterUI (HTTPS)' on port 8480.
> 21/12/17 16:00:41 INFO Utils: Successfully started service 'MasterUI' on port 8080.
>
> 21/12/17 16:03:07 INFO Utils: Successfully started service 'WorkerUI (HTTPS)' on port 8481.
> 21/12/17 16:03:07 INFO Utils: Successfully started service 'WorkerUI' on port 8081.

2022-01-11 07:03 UTC, migruiz4 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set spark.ssl.port "${SPARK_WEBUI_SSL_PORT}"
Although it is dynamic, it should be defined at `spark_env` empty by default:
```
 export SPARK_WEBUI_SSL_PORT="${SPARK_WEBUI_SSL_PORT:-}" 
```
to prevent Bash errors caused by the variable being undefined.

2022-01-21 15:45 UTC, brsolomon-deloitte commented
Haven't forgotten about this one, hoping to turn back to it some time in next few days.

2022-01-23 01:58 UTC, brsolomon-deloitte commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +        spark_conf_set spark.ssl.port "${SPARK_WEBUI_SSL_PORT}"
I believe you, but that is definitely odd to me. The [SSL configuration](https://spark.apache.org/docs/3.2.0/security.html#ssl-configuration) docs imply that `spark.ssl` should "trickle down" to `spark.ssl.standalone` in a hierarchical way.

2022-01-23 01:59 UTC, brsolomon-deloitte commented on 3/debian-10/rootfs/opt/bitnami/scripts/libspark.sh
> +    spark_conf_set spark.ssl.port "${SPARK_WEBUI_SSL_PORT}"
Added in 2ac7381

2022-01-25 06:45 UTC, carrodher commented
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/bitnami-docker-ASSET/blob/master/CONTRIBUTING.md#sign-your-work).

2022-01-31 14:47 UTC, brsolomon-deloitte commented
Squashed and signed.

2022-02-02 09:45 UTC, migruiz4 approved these changes
Looks good to me, thank you for your contribution!

2022-02-02 09:45 UTC, merged